---
title: 'VLBW: Granger Causality Checks'
author: "Lauren Erdman"
date: "October 8, 2017"
output: html_document
---

```{r}
## Load packages
library('lme4')
```

```{r,include=FALSE}
###Set working directory

## Lab computer
#setwd("C:/Users/Lauren/Desktop/OConner collab/Data/")

## Laptop
setwd("C:/Users/Owner/Desktop/Goldenberg Lab/OConnor collab/data/")
```

```{r,echo=FALSE}
###Reading in data
dat <- read.csv("GTA-DoMINO_LongitudinalData.csv",header=TRUE,as.is=TRUE)
# head(dat)
# View(dat)
```

```{r}
## barplot only over unique IDs
static.barplot.vars <- c("DOL","DaysFullEnt","DaysonPN","DaysinFeedInt","Site","MultiB","ROP","CS","SNAP","Sex")
static.barplot.numeric.cat <- c(TRUE,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE)
static.barplot.labels <- c("Days of Life","Number of days it took the infant to achieve full enteral feeding","Number of days the infant received parenteral nutrition","Number of days in the feeding intervention","Site the infant was recruited from","Multiple births;1=single, 2=twins, 3=triplets, 4=quadruplets","Severe retinopathy of prematurity","C-section","Score for Neonatal Acute Physiology II","Sex")

## plot by time "DOL"
spaghetti.vars <- c("Wt_Raw","Lt_Raw","HC_Raw","Wt_Int","Lt_Int","HC_Int","TotalPro","TotalLipid","TotalCarb","TotalEnergy")
spaghetti.labels <- c("Raw weight measurements (in grams)","Raw length measurements (in cm)","Raw head circumference measurements (in cm)","Linearly interpolated weight measurements (in grams)","Linearly interpolated length measurements (in cm)","Linearly interpolated head circumference measurements (in cm)","Daily protein intake from both parenteral and enteral sources (in g/kg/d)","Daily lipid intake from both parenteral and enteral sources (in g/kg/d)","Daily carbohydrate intake from both parenteral and enteral sources (in g/kg/d)","Daily energy intake from both parenteral and enteral sources (in kcal/kg/d)")

```

```{r}
centered.spag.vars <- data.frame(matrix(ncol=length(spaghetti.vars),nrow=nrow(dat)))

for(i in 1:length(spaghetti.vars)){
  centered.spag.vars[,i] <- (dat[,spaghetti.vars[i]] - mean(na.omit(dat[,spaghetti.vars[i]])))/sd(na.omit(dat[,spaghetti.vars[i]]))  
}
names(centered.spag.vars) <- spaghetti.vars
```

####MultiB
```{r}
par(mfrow=c(2,4))

for(i in 4:10){
  in.df <- data.frame(cbind(dat[,c("SubjtID",static.barplot.vars)],centered.spag.vars))
  in.df$DOL <- factor(in.df$DOL,levels = 1:max(in.df$DOL))
  in.df$MultiB <- factor(in.df$MultiB,levels = 1:3)
  in.df$ROP <- factor(in.df$ROP,levels = c("No","Yes"))
  in.df$CS <- factor(in.df$CS,levels = c("No","Yes"))
  in.df$Sex <- factor(in.df$Sex,levels = c("M","F"))
  
  fit <- lmer(in.df[,spaghetti.vars[i]] ~ DOL + DaysFullEnt + MultiB  + ROP + CS + SNAP  + Sex + (1|DOL) + (1|SubjtID) + (1|MultiB),data = in.df)
  summary(fit)
  
  ### predicting curves
  samp <- sample(dat$SubjtID,size = 1)
  
  pred1.df <- data.frame(cbind(samp,
                               rep(1:90,times=3),
                              mean(na.omit(in.df$DaysFullEnt[!duplicated(in.df$SubjtID)])),
                              rep(c(1,2,3),each=90),
                              "No",
                              "No",
                              mean(na.omit(in.df$DaysFullEnt[!duplicated(in.df$SubjtID)])),
                              "M"))
  names(pred1.df) <- c("SubjtID","DOL","DaysFullEnt","MultiB","ROP","CS","SNAP","Sex")
  head(pred1.df)
  
  # pred.df <- rbind(pred1.df,pred2.df)
  pred.df <- pred1.df
  pred.df$DOL <- factor(pred.df$DOL,levels = 1:max(as.numeric(as.character(pred.df$DOL))))
  pred.df$MultiB <- factor(pred.df$MultiB,levels = 1:3)
  pred.df$ROP <- factor(pred.df$ROP,levels = c("No","Yes"))
  pred.df$CS <- factor(pred.df$CS,levels = c("No","Yes"))
  pred.df$Sex <- factor(pred.df$Sex,levels = c("M","F"))
  pred.df$DaysFullEnt <- as.numeric(as.character(pred.df$DaysFullEnt))
  pred.df$SNAP <- as.numeric(as.character(pred.df$SNAP))
  str(pred.df) 
  
  pred.vals <- predict(object = fit,newdata = pred.df,re.form=~0)
  
  plot(x = 1:90,y = pred.vals[1:90],xlab = "Days of Life",ylab = spaghetti.labels[i])
  lines(x = 1:90,y = pred.vals[1:90])
  
  points(x = 1:90,y = pred.vals[91:180],col = "red")
  lines(x = 1:90,y = pred.vals[91:180],col = "red")
  
  points(x = 1:90,y = pred.vals[181:270],col = "blue")
  lines(x = 1:90,y = pred.vals[181:270],col = "blue")
  legend(x = 65,y = summary(pred.vals)[1] + 1,legend = c("Single","Twins","Triplets"),lty=c(1,1),lwd=c(1.5,1.5),col=c("black","red","blue"))
}

```

```{r}
par(mfrow=c(2,4))

for(i in 4:10){
  in.df <- data.frame(cbind(dat[,c("SubjtID",static.barplot.vars)],centered.spag.vars))
  in.df$DOL <- factor(in.df$DOL,levels = 1:max(in.df$DOL))
  in.df$MultiB <- factor(in.df$MultiB,levels = 1:3)
  in.df$ROP <- factor(in.df$ROP,levels = c("No","Yes"))
  in.df$CS <- factor(in.df$CS,levels = c("No","Yes"))
  in.df$Sex <- factor(in.df$Sex,levels = c("M","F"))
  
  fit <- lmer(in.df[,spaghetti.vars[i]] ~ DOL + DaysFullEnt + MultiB  + ROP + CS + SNAP  + Sex + (1|DOL) + (1|SubjtID) + (1|MultiB),data = in.df)
  summary(fit)
  
  ### predicting curves
  samp <- sample(dat$SubjtID,size = 1)
  
  pred1.df <- data.frame(cbind(samp,
                               rep(1:90,times=3),
                              mean(na.omit(in.df$DaysFullEnt[!duplicated(in.df$SubjtID)])),
                              rep(c(1,2,3),each=90),
                              "No",
                              "No",
                              mean(na.omit(in.df$DaysFullEnt[!duplicated(in.df$SubjtID)])),
                              "M"))
  names(pred1.df) <- c("SubjtID","DOL","DaysFullEnt","MultiB","ROP","CS","SNAP","Sex")
  head(pred1.df)
  
  # pred.df <- rbind(pred1.df,pred2.df)
  pred.df <- pred1.df
  pred.df$DOL <- factor(pred.df$DOL,levels = 1:max(as.numeric(as.character(pred.df$DOL))))
  pred.df$MultiB <- factor(pred.df$MultiB,levels = 1:3)
  pred.df$ROP <- factor(pred.df$ROP,levels = c("No","Yes"))
  pred.df$CS <- factor(pred.df$CS,levels = c("No","Yes"))
  pred.df$Sex <- factor(pred.df$Sex,levels = c("M","F"))
  pred.df$DaysFullEnt <- as.numeric(as.character(pred.df$DaysFullEnt))
  pred.df$SNAP <- as.numeric(as.character(pred.df$SNAP))
  str(pred.df) 
  
  pred.vals <- predict(object = fit,newdata = pred.df,re.form=~0)
  
  plot(x = 1:90,y = pred.vals[1:90],xlab = "Days of Life",ylab = spaghetti.labels[i])
  lines(x = 1:90,y = pred.vals[1:90])
  
  points(x = 1:90,y = pred.vals[91:180],col = "red")
  lines(x = 1:90,y = pred.vals[91:180],col = "red")
  
  points(x = 1:90,y = pred.vals[181:270],col = "blue")
  lines(x = 1:90,y = pred.vals[181:270],col = "blue")
  legend(x = 65,y = summary(pred.vals)[1] + 1,legend = c("Single","Twins","Triplets"),lty=c(1,1),lwd=c(1.5,1.5),col=c("black","red","blue"))
}

```

####ROP?
```{r}

par(mfrow=c(2,4))

for(i in 4:10){
  in.df <- data.frame(cbind(dat[,c("SubjtID",static.barplot.vars)],centered.spag.vars))

  in.df$DOL <- factor(in.df$DOL,levels = 1:max(in.df$DOL))
  in.df$MultiB <- factor(in.df$MultiB,levels = 1:3)
  in.df$ROP <- factor(in.df$ROP,levels = c("No","Yes"))
  in.df$CS <- factor(in.df$CS,levels = c("No","Yes"))
  in.df$Sex <- factor(in.df$Sex,levels = c("M","F"))
  
  fit <- lmer(in.df[,spaghetti.vars[i]] ~ DOL + DaysFullEnt + MultiB  + ROP + CS + SNAP  + Sex + (1|DOL) + (1|SubjtID) + (1|ROP),data = in.df)
  summary(fit)
  
  ### predicting curves
  samp <- sample(dat$SubjtID,size = 1)
  
  pred1.df <- data.frame(cbind(samp,
                               rep(1:90,times=2),
                              mean(na.omit(in.df$DaysFullEnt[!duplicated(in.df$SubjtID)])),
                              rep(1,180),
                              rep(c("No","Yes"),each=90),
                              "No",
                              mean(na.omit(in.df$DaysFullEnt[!duplicated(in.df$SubjtID)])),
                              "M"))
  names(pred1.df) <- c("SubjtID","DOL","DaysFullEnt","MultiB","ROP","CS","SNAP","Sex")
  head(pred1.df)
  
  # pred.df <- rbind(pred1.df,pred2.df)
  pred.df <- pred1.df
  pred.df$DOL <- factor(pred.df$DOL,levels = 1:max(as.numeric(as.character(pred.df$DOL))))
  pred.df$MultiB <- factor(pred.df$MultiB,levels = 1:3)
  pred.df$ROP <- factor(pred.df$ROP,levels = c("No","Yes"))
  pred.df$CS <- factor(pred.df$CS,levels = c("No","Yes"))
  pred.df$Sex <- factor(pred.df$Sex,levels = c("M","F"))
  pred.df$DaysFullEnt <- as.numeric(as.character(pred.df$DaysFullEnt))
  pred.df$SNAP <- as.numeric(as.character(pred.df$SNAP))
  str(pred.df) 
  
  pred.vals <- predict(object = fit,newdata = pred.df)
  
  plot(x = 1:90,y = pred.vals[1:90],xlab = "Days of Life",ylab = spaghetti.labels[i], main = spaghetti.vars[i])
  lines(x = 1:90,y = pred.vals[1:90])
  
  points(x = 1:90,y = pred.vals[91:180],col = "red")
  lines(x = 1:90,y = pred.vals[91:180],col = "red")
  legend(x = 65,y = summary(pred.vals)[1] + 1,legend = c("No","Yes"),lty=c(1,1),lwd=c(1.5,1.5),col=c("black","red"))
}

```

####CESARIAN?
```{r}
par(mfrow=c(2,4))

for(i in 4:10){
  in.df <- data.frame(cbind(dat[,c("SubjtID",static.barplot.vars)],centered.spag.vars))
  head(in.df)
  str(in.df)
  in.df$DOL <- factor(in.df$DOL,levels = 1:max(in.df$DOL))
  in.df$MultiB <- factor(in.df$MultiB,levels = 1:3)
  in.df$ROP <- factor(in.df$ROP,levels = c("No","Yes"))
  in.df$CS <- factor(in.df$CS,levels = c("No","Yes"))
  in.df$Sex <- factor(in.df$Sex,levels = c("M","F"))
  
  fit <- lmer(in.df[,spaghetti.vars[i]] ~ DOL + DaysFullEnt + MultiB  + ROP + CS + SNAP  + Sex + (1|DOL) + (1|SubjtID) + (1|CS),data = in.df)
  summary(fit)
  
  ### predicting curves
  samp <- sample(dat$SubjtID,size = 1)
  
  pred1.df <- data.frame(cbind(samp,
                               rep(1:90,times=2),
                              mean(na.omit(in.df$DaysFullEnt[!duplicated(in.df$SubjtID)])),
                              rep(1,180),
                              "No",
                              rep(c("No","Yes"),each=90),
                              mean(na.omit(in.df$DaysFullEnt[!duplicated(in.df$SubjtID)])),
                              "M"))
  names(pred1.df) <- c("SubjtID","DOL","DaysFullEnt","MultiB","ROP","CS","SNAP","Sex")
  head(pred1.df)
  
  # pred.df <- rbind(pred1.df,pred2.df)
  pred.df <- pred1.df
  pred.df$DOL <- factor(pred.df$DOL,levels = 1:max(as.numeric(as.character(pred.df$DOL))))
  pred.df$MultiB <- factor(pred.df$MultiB,levels = 1:3)
  pred.df$ROP <- factor(pred.df$ROP,levels = c("No","Yes"))
  pred.df$CS <- factor(pred.df$CS,levels = c("No","Yes"))
  pred.df$Sex <- factor(pred.df$Sex,levels = c("M","F"))
  pred.df$DaysFullEnt <- as.numeric(as.character(pred.df$DaysFullEnt))
  pred.df$SNAP <- as.numeric(as.character(pred.df$SNAP))
  str(pred.df) 
  
  pred.vals <- predict(object = fit,newdata = pred.df)
  
  plot(x = 1:90,y = pred.vals[1:90],xlab = "Days of Life",ylab = spaghetti.labels[i])
  lines(x = 1:90,y = pred.vals[1:90])
  
  points(x = 1:90,y = pred.vals[91:180],col = "red")
  lines(x = 1:90,y = pred.vals[91:180],col = "red")
  legend(x = 65,y = summary(pred.vals)[1] + 1,legend = c("No","Yes"),lty=c(1,1),lwd=c(1.5,1.5),col=c("black","red"))
}

```

####DaysFullEnt
```{r}

par(mfrow=c(2,4))

for(i in 4:10){
  in.df <- data.frame(cbind(dat[,c("SubjtID",static.barplot.vars)],centered.spag.vars))
  head(in.df)
  str(in.df)
  in.df$DOL <- factor(in.df$DOL,levels = 1:max(in.df$DOL))
  in.df$MultiB <- factor(in.df$MultiB,levels = 1:3)
  in.df$ROP <- factor(in.df$ROP,levels = c("No","Yes"))
  in.df$CS <- factor(in.df$CS,levels = c("No","Yes"))
  in.df$Sex <- factor(in.df$Sex,levels = c("M","F"))
  
  fit <- lmer(in.df[,spaghetti.vars[i]] ~ DOL + DaysFullEnt + MultiB  + ROP + CS + SNAP  + Sex + (1|DOL) + (1|SubjtID),data = in.df)
  summary(fit)
  
  ### predicting curves
  samp <- sample(dat$SubjtID,size = 1)
  
  pred1.df <- data.frame(cbind(samp,
                               rep(1:90,times=3),
                              rep(c(summary(na.omit(in.df$DaysFullEnt[!duplicated(in.df$SubjtID)]))[2],
                                    summary(na.omit(in.df$DaysFullEnt[!duplicated(in.df$SubjtID)]))[3],
                                    summary(na.omit(in.df$DaysFullEnt[!duplicated(in.df$SubjtID)]))[5]),each=90),
                              1,
                              "No",
                              "No",
                              mean(na.omit(in.df$DaysFullEnt[!duplicated(in.df$SubjtID)])),
                              "M"))
  names(pred1.df) <- c("SubjtID","DOL","DaysFullEnt","MultiB","ROP","CS","SNAP","Sex")
  head(pred1.df)
  
  # pred.df <- rbind(pred1.df,pred2.df)
  pred.df <- pred1.df
  pred.df$DOL <- factor(pred.df$DOL,levels = 1:max(as.numeric(as.character(pred.df$DOL))))
  pred.df$MultiB <- factor(pred.df$MultiB,levels = 1:3)
  pred.df$ROP <- factor(pred.df$ROP,levels = c("No","Yes"))
  pred.df$CS <- factor(pred.df$CS,levels = c("No","Yes"))
  pred.df$Sex <- factor(pred.df$Sex,levels = c("M","F"))
  pred.df$DaysFullEnt <- as.numeric(as.character(pred.df$DaysFullEnt))
  pred.df$SNAP <- as.numeric(as.character(pred.df$SNAP))
  str(pred.df) 
  
  pred.vals <- predict(object = fit,newdata = pred.df,re.form=~0)
  
  plot(x = 1:90,y = pred.vals[1:90],xlab = "Days of Life",ylab = spaghetti.labels[i])
  lines(x = 1:90,y = pred.vals[1:90])
  
  points(x = 1:90,y = pred.vals[91:180],col = "red")
  lines(x = 1:90,y = pred.vals[91:180],col = "red")
  
  points(x = 1:90,y = pred.vals[181:270],col = "blue")
  lines(x = 1:90,y = pred.vals[181:270],col = "blue")
  legend(x = 65,y = 0,legend = c("1stQ","Median","3rdQ"),lty=c(1,1),lwd=c(1.5,1.5),col=c("black","red","blue"))
}

```

####SEX
```{r}
i=3
par(mfrow=c(2,4))

for(i in 4:10){
  in.df <- data.frame(cbind(dat[,c("SubjtID",static.barplot.vars)],centered.spag.vars))
  head(in.df)
  str(in.df)
  in.df$DOL <- factor(in.df$DOL,levels = 1:max(in.df$DOL))
  in.df$MultiB <- factor(in.df$MultiB,levels = 1:3)
  in.df$ROP <- factor(in.df$ROP,levels = c("No","Yes"))
  in.df$CS <- factor(in.df$CS,levels = c("No","Yes"))
  in.df$Sex <- factor(in.df$Sex,levels = c("M","F"))
  
  fit <- lmer(in.df[,spaghetti.vars[i]] ~ DOL + DaysFullEnt + MultiB  + ROP + CS + SNAP  + Sex + (1|DOL) + (1|SubjtID) + (1|Sex),data = in.df)
  summary(fit)
  
  ### predicting curves
  samp <- sample(dat$SubjtID,size = 1)
  
  pred1.df <- data.frame(cbind(samp,
                               rep(1:90,times=2),
                              mean(na.omit(in.df$DaysFullEnt[!duplicated(in.df$SubjtID)])),
                              rep(1,180),
                              "No",
                              "No",
                              mean(na.omit(in.df$DaysFullEnt[!duplicated(in.df$SubjtID)])),
                              rep(c("M","F"),each=90)))
  names(pred1.df) <- c("SubjtID","DOL","DaysFullEnt","MultiB","ROP","CS","SNAP","Sex")
  head(pred1.df)
  
  # pred.df <- rbind(pred1.df,pred2.df)
  pred.df <- pred1.df
  pred.df$DOL <- factor(pred.df$DOL,levels = 1:max(as.numeric(as.character(pred.df$DOL))))
  pred.df$MultiB <- factor(pred.df$MultiB,levels = 1:3)
  pred.df$ROP <- factor(pred.df$ROP,levels = c("No","Yes"))
  pred.df$CS <- factor(pred.df$CS,levels = c("No","Yes"))
  pred.df$Sex <- factor(pred.df$Sex,levels = c("M","F"))
  pred.df$DaysFullEnt <- as.numeric(as.character(pred.df$DaysFullEnt))
  pred.df$SNAP <- as.numeric(as.character(pred.df$SNAP))
  str(pred.df) 
  
  pred.vals <- predict(object = fit,newdata = pred.df)
  
  plot(x = 1:90,y = pred.vals[1:90],xlab = "Days of Life",main = spaghetti.vars[i],ylab=spaghetti.labels[i])
  lines(x = 1:90,y = pred.vals[1:90])
  
  points(x = 1:90,y = pred.vals[91:180],col = "red")
  lines(x = 1:90,y = pred.vals[91:180],col = "red")
  legend(x = 65,y = 0,legend = c("Male","Female"),lty=c(1,1),lwd=c(1.5,1.5),col=c("black","red"))
}

head(dat)

```


#
# 
#   Average trajectories plotted on top of each other
#
#

```{r}
spaghetti.labels
i = 2
pred.plot.curve <- function(i){
  ## fitting curves
  # head(dat)
  in.df <- data.frame(cbind(dat[,c("SubjtID",static.barplot.vars)],centered.spag.vars))
  # head(in.df)
  # str(in.df)
  in.df$DOL <- factor(in.df$DOL,levels = 1:max(in.df$DOL))
  in.df$MultiB <- factor(in.df$MultiB,levels = 1:3)
  in.df$ROP <- factor(in.df$ROP,levels = c("No","Yes"))
  in.df$CS <- factor(in.df$CS,levels = c("No","Yes"))
  in.df$Sex <- factor(in.df$Sex,levels = c("M","F"))
  
  fit <- lmer(in.df[,spaghetti.vars[i]] ~ DOL + DaysFullEnt + MultiB  + ROP + CS + SNAP  + Sex + (1|DOL) + (1|SubjtID),data = in.df)
  # summary(fit)
  
  ### predicting curves
  samp <- sample(dat$SubjtID,size = 1)
  
  pred1.df <- data.frame(cbind(samp,
                               1:90,
                              mean(na.omit(in.df$DaysFullEnt[!duplicated(in.df$SubjtID)])),
                              1,
                              "No",
                              "No",
                              mean(na.omit(in.df$DaysFullEnt[!duplicated(in.df$SubjtID)])),
                              "M"))
  names(pred1.df) <- c("SubjtID","DOL","DaysFullEnt","MultiB","ROP","CS","SNAP","Sex")
  # head(pred1.df)
  
  # pred.df <- rbind(pred1.df,pred2.df)
  pred.df <- pred1.df
  pred.df$DOL <- factor(pred.df$DOL,levels = 1:max(as.numeric(as.character(pred.df$DOL))))
  pred.df$MultiB <- factor(pred.df$MultiB,levels = 1:3)
  pred.df$ROP <- factor(pred.df$ROP,levels = c("No","Yes"))
  pred.df$CS <- factor(pred.df$CS,levels = c("No","Yes"))
  pred.df$Sex <- factor(pred.df$Sex,levels = c("M","F"))
  pred.df$DaysFullEnt <- as.numeric(as.character(pred.df$DaysFullEnt))
  pred.df$SNAP <- as.numeric(as.character(pred.df$SNAP))
  # str(pred.df) 
  
  pred.vals1 <- predict(object = fit,newdata = pred.df,re.form=~0)
  
  plot(x = 1:90,y = pred.vals1,xlab = "Days of Life",ylab = spaghetti.labels[i])
  lines(x = 1:90,y = pred.vals1)
  
  return(pred.vals1)  
}

pred.curves <- sapply(2:length(spaghetti.vars),pred.plot.curve)

# png("test.png")
par(mfrow=c(ncol(pred.curves),ncol(pred.curves)))

par(mfrow=c(3,4))
for(i in 1:3){
  for(j in 6:9){
    plot(x = 1:90,y=pred.curves[,i],xlab="Days of Life",ylab="z-score",main=paste0(spaghetti.vars[i+1]," in black \n",spaghetti.vars[j + 1]," in red"))
    lines(x = 1:90,y=pred.curves[,i])
    
    points(x = 1:90,y=pred.curves[,j],col="red")
    lines(x = 1:90,y=pred.curves[,j],col = "red")
  }
}
# dev.off()

# names(pred.curves) <- 



```
